// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Curry from "bs-platform/lib/es6/curry.js";
import * as Caml_option from "bs-platform/lib/es6/caml_option.js";

function Make(Id, State) {
  var replica = function (id) {
    return {
            id: id,
            state: State.empty
          };
  };
  var join = function (p, q) {
    var state = Curry._2(State.join, p.state, q.state);
    var id = p.id;
    if (id !== undefined) {
      var id$1 = Caml_option.valFromOption(id);
      q.id !== undefined;
      return {
              id: Caml_option.some(id$1),
              state: state
            };
    }
    var id$2 = q.id;
    if (id$2 !== undefined) {
      return {
              id: Caml_option.some(Caml_option.valFromOption(id$2)),
              state: state
            };
    } else {
      return {
              id: undefined,
              state: state
            };
    }
  };
  return {
          replica: replica,
          join: join
        };
}

function Pair(A, B) {
  var empty_000 = A.empty;
  var empty_001 = B.empty;
  var empty = /* tuple */[
    empty_000,
    empty_001
  ];
  var join = function (param, param$1) {
    return /* tuple */[
            Curry._2(A.join, param[0], param$1[0]),
            Curry._2(B.join, param[1], param$1[1])
          ];
  };
  return {
          empty: empty,
          join: join
        };
}

function LexicographicPair(A, B) {
  var empty_000 = A.empty;
  var empty_001 = B.empty;
  var empty = /* tuple */[
    empty_000,
    empty_001
  ];
  var join = function (param, param$1) {
    var b$prime = param$1[1];
    var a$prime = param$1[0];
    var b = param[1];
    var a = param[0];
    var priority = Curry._2(A.compare, a, a$prime);
    switch (priority) {
      case /* Left */0 :
          return /* tuple */[
                  a,
                  b
                ];
      case /* Both */1 :
          return /* tuple */[
                  a,
                  Curry._2(B.join, b, b$prime)
                ];
      case /* Neither */2 :
          return /* tuple */[
                  Curry._2(A.join, a, a$prime),
                  B.empty
                ];
      case /* Right */3 :
          return /* tuple */[
                  a$prime,
                  b$prime
                ];
      
    }
  };
  return {
          empty: empty,
          join: join
        };
}

export {
  Make ,
  Pair ,
  LexicographicPair ,
  
}
/* No side effect */
