// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Curry from "bs-platform/lib/es6/curry.js";
import * as Caml_obj from "bs-platform/lib/es6/caml_obj.js";
import * as Caml_option from "bs-platform/lib/es6/caml_option.js";

function Make(State) {
  var replicaGenerator = function (init, id) {
    return {
            id: Caml_option.some(id),
            state: Curry._3(State.add, id, init, State.empty)
          };
  };
  var join = function (p, q) {
    var state = Curry._3(State.merge, (function (param) {
            return Caml_obj.caml_max;
          }), p.state, q.state);
    var id = p.id;
    if (id !== undefined) {
      var id$1 = Caml_option.valFromOption(id);
      q.id !== undefined;
      return {
              id: Caml_option.some(id$1),
              state: state
            };
    }
    var id$2 = q.id;
    if (id$2 !== undefined) {
      return {
              id: Caml_option.some(Caml_option.valFromOption(id$2)),
              state: state
            };
    } else {
      return {
              id: undefined,
              state: state
            };
    }
  };
  return {
          replicaGenerator: replicaGenerator,
          join: join
        };
}

export {
  Make ,
  
}
/* No side effect */
