// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as $$Map from "bs-platform/lib/es6/map.js";
import * as Block from "bs-platform/lib/es6/block.js";
import * as Curry from "bs-platform/lib/es6/curry.js";
import * as Caml_obj from "bs-platform/lib/es6/caml_obj.js";
import * as Caml_option from "bs-platform/lib/es6/caml_option.js";
import * as Crdt$DeltaCrdts from "./Crdt.bs.js";

function State(Data) {
  var empty = Data.empty;
  var join = function (p, q) {
    return Curry._3(Data.merge, (function (param) {
                  return Caml_obj.caml_max;
                }), p, q);
  };
  var increment = function (state, id) {
    return Curry._3(Data.add, id, Curry._2(Data.find, id, state) + 1 | 0, empty);
  };
  var value = function (state) {
    return Curry._3(Data.fold, (function (param, v, accum) {
                  return v + accum | 0;
                }), state, 0);
  };
  return {
          empty: empty,
          join: join,
          increment: increment,
          value: value
        };
}

function Make(Id) {
  var Data = $$Map.Make(Id);
  var empty = Data.empty;
  var join = function (p, q) {
    return Curry._3(Data.merge, (function (param) {
                  return Caml_obj.caml_max;
                }), p, q);
  };
  var increment = function (state, id) {
    return Curry._3(Data.add, id, Curry._2(Data.find, id, state) + 1 | 0, empty);
  };
  var value = function (state) {
    return Curry._3(Data.fold, (function (param, v, accum) {
                  return v + accum | 0;
                }), state, 0);
  };
  var State = {
    empty: empty,
    join: join,
    increment: increment,
    value: value
  };
  var partial_arg = Crdt$DeltaCrdts.Make;
  var include = partial_arg(Id, State);
  var deltaOfState = include.deltaOfState;
  var mutate = include.mutate;
  var replica = function (id) {
    return {
            id: Caml_option.some(id),
            state: Curry._3(Data.add, id, 0, empty)
          };
  };
  var value$1 = function (patch) {
    return value(patch.state);
  };
  var increment$1 = function (replica) {
    var id = replica.id;
    if (id !== undefined) {
      return Curry._2(mutate, replica, Curry._1(deltaOfState, increment(replica.state, Caml_option.valFromOption(id))));
    } else {
      return /* Invalid */Block.__(1, [
                /* replica */replica,
                /* delta */undefined
              ]);
    }
  };
  return {
          Data: Data,
          State: State,
          deltaOfState: deltaOfState,
          join: include.join,
          mutate: mutate,
          initialValue: 0,
          replica: replica,
          value: value$1,
          increment: increment$1
        };
}

export {
  State ,
  Make ,
  
}
/* No side effect */
