// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Caml_obj from "bs-platform/lib/es6/caml_obj.js";
import * as Crdt$DeltaCrdts from "./Crdt.bs.js";

var compare = Caml_obj.caml_compare;

var Int = {
  empty: 0,
  compare: compare
};

var include = Crdt$DeltaCrdts.ChoosableOfBaseOrderedType(Int);

var TimelikeCounterState_empty = include.empty;

var TimelikeCounterState_compare = include.compare;

var TimelikeCounterState_choose = include.choose;

var TimelikeCounterState_join = include.join;

var TimelikeCounterState = {
  Int: Int,
  empty: TimelikeCounterState_empty,
  compare: TimelikeCounterState_compare,
  choose: TimelikeCounterState_choose,
  join: TimelikeCounterState_join
};

export {
  TimelikeCounterState ,
  
}
/* include Not a pure module */
