// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Curry from "bs-platform/lib/es6/curry.js";
import * as Caml_obj from "bs-platform/lib/es6/caml_obj.js";
import * as Crdt$DeltaCrdts from "./Crdt.bs.js";

var compare = Caml_obj.caml_compare;

var Int = {
  compare: compare
};

var include = Crdt$DeltaCrdts.ComparableOfOrderedType(Int);

var compare$1 = include.compare;

function join(t, t$prime) {
  var match = Curry._2(compare$1, t, t$prime);
  if (match.tag === /* Neither */3) {
    return 0;
  } else {
    return match[0];
  }
}

var TimelikeCounterState = {
  Int: Int,
  compare: compare$1,
  empty: 0,
  join: join
};

export {
  TimelikeCounterState ,
  
}
/* include Not a pure module */
